#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/your_database_name?useSSL=false&serverTimezone=UTC
#    driverClassName: com.mysql.cj.jdbc.Driver
#    username: your_username
#    password: your_password
#  jpa:
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#    hibernate:
#      ddl-auto: update

server:
  port: 8089