server:
  port: 8883


spring:
  elasticsearch:
    uris: http://localhost:9200
    username: elastic
    password: 5KH90zCh
  ai:
    chat:
      client:
        enabled: false
    model:
      embedding: ollama
    ollama:
      init:
        pull-model-strategy: never
      base-url: http://localhost:11434
      embedding:
        options:
          model: qwen3-embedding:0.6b
    vectorstore:
      elasticsearch:
        initialize-schema: true
        index-name: rag_store
        dimensions: 1024
        similarity: cosine
        embedding-field-name: q_1024_vec
    openai:
      api-key: test
#debug: true


model:
  ppStructureV3:
    url: http://localhost:8885/layout-parsing


s3:
  endpoint: http://192.168.31.131:8886
  access-key: minioadmin
  secret-key: minioadmin
  default-bucket-name: rag
  async-netty-pool:
    core-threads: 10
    max-threads: 50
    connection-timeout: 100
    max-pending-connection-acquires: 1000



